ARG builder_base="anyakichi/yocto-builder"
FROM ${builder_base}

RUN \
  apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    autoconf2.13 \
    clang \
    clang-3.9 \
    llvm \
    llvm-3.9 \
  && rm -rf /var/lib/apt/lists/*

USER builder
COPY esr60/firefox.conf /home/builder/

USER root
COPY esr60/buildenv.d/* /etc/buildenv.d/

ENV FIREFOX_VERSION=60
