#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

resolve_base()
{
    case "$1" in
        ek874-*|hihope-rzg2*)
            echo "anyakichi/yocto-rzg2-builder:$1"
            ;;
    esac
}

build()
{
    tag=$1
    base=$(resolve_base "${tag%-*}")
    version=${tag##*-}

    docker build \
        --build-arg builder_base=${base} \
        -t ${DOCKER_REPO}:${tag} \
        -f ${version}/Dockerfile ${version}
}

if [ $# -eq 0 ]; then
    build "${DOCKER_TAG}"
else
    build "$@"
fi
