#!/bin/bash

_push_rzg2()
{
    machine=$1
    branch=$2
    version=$3

    tag="${machine}-$(echo "${branch}" \
            | sed -e 's/^BSP-//' -e 's/-update/u/' -e 's/\.//g' -e 's/-RT/rt/'\
            )-${version}"

    docker push "${DOCKER_REPO}:${tag}"
}

if [ "${DOCKER_TAG}" = "rzg2" ]; then
    for v in esr60 esr68 esr78 release; do
        docker push "${DOCKER_REPO}:rzg2-${v}"

        for b in BSP-1.0.0 BSP-1.0.1{,-update1} BSP-1.0.2{,-update1} \
                BSP-1.0.3{,-RT} BSP-1.0.4{,-RT}{,-update1} \
                BSP-1.0.5{,-RT{,-update1}} BSP-1.0.6{,-RT,-update1} \
                BSP-1.0.7{,-RT} BSP-1.0.8; do
            _push_rzg2 ek874 "$b" "$v"
            if [[ ! "$b" < BSP-1.0.1 ]]; then
                _push_rzg2 hihope-rzg2m "$b" "$v"
            fi
            if [[ ! "$b" < BSP-1.0.2 ]]; then
                _push_rzg2 hihope-rzg2n "$b" "$v"
            fi
            if [[ ! "$b" < BSP-1.0.4 ]]; then
                _push_rzg2 hihope-rzg2h "$b" "$v"
            fi
        done
    done

    docker push "${DOCKER_REPO}:rzg2"
else
    docker push "${DOCKER_TAG}"
fi
