name: Publish Docker image
on:
  push:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: [[68, esr68], [78, esr78], [91, esr91], [102, esr102], [115, release]]
        base:
          [
            [ek874-108, "anyakichi/yocto-rzg2-builder:ek874-108"],
            [hihope-rzg2h-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-108"],
            [hihope-rzg2m-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-108"],
            [hihope-rzg2n-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-108"],
            [ek874-1010u1, "anyakichi/yocto-rzg2-builder:ek874-1010u1"],
            [hihope-rzg2h-1010u1, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-1010u1"],
            [hihope-rzg2m-1010u1, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-1010u1"],
            [hihope-rzg2n-1010u1, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-1010u1"],
            [smarc-rzg2l-14, "anyakichi/yocto-rzg2-builder:smarc-rzg2l-14"],
            [smarc-rzg2lc-14, "anyakichi/yocto-rzg2-builder:smarc-rzg2lc-14"],
            [smarc-rzg2ul-14, "anyakichi/yocto-rzg2-builder:smarc-rzg2ul-14"],
            [ek874-301, "anyakichi/yocto-rzg2-builder:ek874-301"],
            [hihope-rzg2h-301, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-301"],
            [hihope-rzg2m-301, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-301"],
            [hihope-rzg2n-301, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-301"],
            [smarc-rzg2l-301, "anyakichi/yocto-rzg2-builder:smarc-rzg2l-301"],
            [smarc-rzg2lc-301, "anyakichi/yocto-rzg2-builder:smarc-rzg2lc-301"],
            [smarc-rzg2ul-301, "anyakichi/yocto-rzg2-builder:smarc-rzg2ul-301"],
            [ek874-303, "anyakichi/yocto-rzg2-builder:ek874-303"],
            [hihope-rzg2h-303, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-303"],
            [hihope-rzg2m-303, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-303"],
            [hihope-rzg2n-303, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-303"],
            [smarc-rzg2l-303, "anyakichi/yocto-rzg2-builder:smarc-rzg2l-303"],
            [smarc-rzg2lc-303, "anyakichi/yocto-rzg2-builder:smarc-rzg2lc-303"],
            [smarc-rzg2ul-303, "anyakichi/yocto-rzg2-builder:smarc-rzg2ul-303"],
            [ek874-305, "anyakichi/yocto-rzg2-builder:ek874-305"],
            [hihope-rzg2h-305, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-305"],
            [hihope-rzg2m-305, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-305"],
            [hihope-rzg2n-305, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-305"],
            [smarc-rzg2l-305, "anyakichi/yocto-rzg2-builder:smarc-rzg2l-305"],
            [smarc-rzg2lc-305, "anyakichi/yocto-rzg2-builder:smarc-rzg2lc-305"],
            [smarc-rzg2ul-305, "anyakichi/yocto-rzg2-builder:smarc-rzg2ul-305"],
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/gecko-embedded-builder
            ghcr.io/anyakichi/gecko-embedded-builder
          tags: ${{ matrix.base[0] }}-${{ matrix.firefox[1] }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            builder_base=${{ matrix.base[1] }}
            firefox_version=${{ matrix.firefox[0] }}
            subdir=${{ matrix.firefox[1] }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_and_push_esr60:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base:
          [
            [ek874-108, "anyakichi/yocto-rzg2-builder:ek874-108"],
            [hihope-rzg2h-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-108"],
            [hihope-rzg2m-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-108"],
            [hihope-rzg2n-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-108"],
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/gecko-embedded-builder
            ghcr.io/anyakichi/gecko-embedded-builder
          tags: ${{ matrix.base[0] }}-esr60
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.esr60
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            builder_base=${{ matrix.base[1] }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
